<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="NSubstitute" Version="5.1.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\ComfyBot.Application\ComfyBot.Application.csproj" />
  </ItemGroup>

</Project>
